"""revision template."""
revision: str = "b66d35cdf832"
down_revision: str | None = "003_add_business_geo_fields"
branch_labels: str | None = "None"
depends_on: str | None = "None"

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b66d35cdf832'
down_revision: Union[str, None] = '003_add_business_geo_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), server_default='email', nullable=False))
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.drop_column('users', 'auth_provider')
    op.alter_column('businesses', 'phone_number',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###