"""revision template."""
revision: str = "e48955c85206"
down_revision: str | None = "None"
branch_labels: str | None = "None"
depends_on: str | None = "None"

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e48955c85206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_result', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('business_settings',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('operating_hours', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('appointment_slots', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('sms_aliases', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('notification_preferences', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('catalog_items',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_business_category', 'catalog_items', ['business_id', 'category', 'is_available'], unique=False)
    op.create_table('customers',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'phone_number', name='uq_business_customer_phone')
    )
    op.create_index('idx_customer_business_phone', 'customers', ['business_id', 'phone_number'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('message_sid', sa.String(length=64), nullable=False),
    sa.Column('from_number', sa.String(length=64), nullable=False),
    sa.Column('to_number', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_sid')
    )
    op.create_index('idx_inbound_business_time', 'inbound_messages', ['business_id', 'created_at'], unique=False)
    op.create_table('inventory_items',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('is_low_stock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'item_name', name='uq_business_inventory_item_name')
    )
    op.create_index('idx_inventory_low', 'inventory_items', ['business_id', 'is_low_stock'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('to_number', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('message_sid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbound_business', 'outbound_messages', ['business_id', 'created_at'], unique=False)
    op.create_index('idx_outbound_sid', 'outbound_messages', ['message_sid'], unique=False)
    op.create_table('users',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversation_states',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('from_number', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_from', 'conversation_states', ['business_id', 'from_number'], unique=False)
    op.create_table('intent_predictions',
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('entities', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('candidate_intents', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('classifier_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['inbound_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_events',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_events_item', 'inventory_events', ['item_id', 'created_at'], unique=False)
    op.create_table('inventory_thresholds',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('low_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('auto_alert', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('orders',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'order_number', name='uq_business_order_number')
    )
    op.create_index('idx_order_business_status', 'orders', ['business_id', 'status'], unique=False)
    op.create_table('reservations',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('table_or_slot', sa.String(length=50), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reservation_customer', 'reservations', ['business_id', 'customer_name'], unique=False)
    op.create_index('idx_reservation_time', 'reservations', ['business_id', 'reserved_at', 'status'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_status_history')
    op.drop_table('order_items')
    op.drop_index('idx_reservation_time', table_name='reservations')
    op.drop_index('idx_reservation_customer', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('idx_order_business_status', table_name='orders')
    op.drop_table('orders')
    op.drop_table('inventory_thresholds')
    op.drop_index('idx_inv_events_item', table_name='inventory_events')
    op.drop_table('inventory_events')
    op.drop_table('intent_predictions')
    op.drop_index('idx_conversation_from', table_name='conversation_states')
    op.drop_table('conversation_states')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_outbound_sid', table_name='outbound_messages')
    op.drop_index('idx_outbound_business', table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index('idx_inventory_low', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('idx_inbound_business_time', table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_index('idx_customer_business_phone', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_catalog_business_category', table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_table('business_settings')
    op.drop_table('webhook_events')
    op.drop_table('businesses')
    # ### end Alembic commands ###